version: "3.9"
services:
  app:
    build: .
    depends_on:
      - mysql
    ports:
      - 8080:80
    volumes:
      - .:/srv/app
  mysql:
    image: mysql:5.7
    ports:
      - 13306:3306
    volumes:
      - mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: homestead
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
volumes:
  mysql:
    driver: local
